sudo: required
services:
  - docker

before_install:
  - docker build -t nikola/docker-react -f Dockerfile.dev .

script:
  #- docker run -e CI=true nikola/docker-react npm run test
  - docker run nikola/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  name: "frontend"
  env: "Frontend-env"
  bucket_name: elasticbeanstalk-us-east-1-739949737839
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"